# Regenerates arm/font.h: two antialiased bitmap fonts (8-bit coverage, ASCII
# 32..126, proportional advances) rendered with System.Drawing. Bold weights and
# 19/26 px sizes were chosen for 480i: bold strokes are two scanlines or more,
# which keeps interlace flicker down on a CRT.
#   powershell -File arm\genfont.ps1
$out = Join-Path $PSScriptRoot "font.h"
Add-Type -AssemblyName System.Drawing
function Gen($name, $family, $px, $cellW, $cellH, $style) {
  $sb = New-Object System.Text.StringBuilder
  $font = New-Object System.Drawing.Font($family, [float]$px, $style, [System.Drawing.GraphicsUnit]::Pixel)
  [void]$sb.AppendLine("/* $family ${px}px $style, cells ${cellW}x${cellH}, 8-bit coverage, ASCII 32..126, proportional */")
  [void]$sb.AppendLine("#define ${name}_W $cellW")
  [void]$sb.AppendLine("#define ${name}_H $cellH")
  $bmp = New-Object System.Drawing.Bitmap($cellW, $cellH, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
  $g = [System.Drawing.Graphics]::FromImage($bmp)
  $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit
  $fmt = New-Object System.Drawing.StringFormat([System.Drawing.StringFormat]::GenericTypographic)
  $fmt.FormatFlags = $fmt.FormatFlags -bor [System.Drawing.StringFormatFlags]::MeasureTrailingSpaces
  $adv = New-Object System.Text.StringBuilder
  [void]$adv.Append("static const unsigned char ${name}_adv[95] = {")
  $data = New-Object System.Text.StringBuilder
  [void]$data.AppendLine("static const unsigned char ${name}[95][$cellH * $cellW] = {")
  for ($c = 32; $c -le 126; $c++) {
    $g.Clear([System.Drawing.Color]::Black)
    $str = [string][char]$c
    $g.DrawString($str, $font, [System.Drawing.Brushes]::White, [float]1, [float]0, $fmt)
    $w = [Math]::Round($g.MeasureString($str, $font, 1000, $fmt).Width)
    if ($w -lt 3) { $w = [Math]::Round($px * 0.28) }
    [void]$adv.Append("$w,")
    $line = New-Object System.Text.StringBuilder
    [void]$line.Append("{")
    for ($y = 0; $y -lt $cellH; $y++) { for ($x = 0; $x -lt $cellW; $x++) { [void]$line.Append($bmp.GetPixel($x,$y).R); [void]$line.Append(",") } }
    [void]$line.Append("},")
    [void]$data.AppendLine($line.ToString())
  }
  [void]$data.AppendLine("};")
  [void]$adv.AppendLine("};")
  $g.Dispose(); $bmp.Dispose()
  return $sb.ToString() + $adv.ToString() + $data.ToString()
}
$s = "/* generated by arm/genfont.ps1 (System.Drawing); glyphs drawn at x=1 in the cell, advance in _adv */`n"
$s += Gen "font_big" "Segoe UI" 26 28 32 ([System.Drawing.FontStyle]::Bold)
$s += Gen "font_small" "Segoe UI" 19 20 24 ([System.Drawing.FontStyle]::Bold)
[System.IO.File]::WriteAllText($out, $s)
"wrote $out ($((Get-Item $out).Length) bytes)"
